#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autodealer.dev.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AUTODEALER.DEV")]
	public partial class AutoDealerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertApiKey(ApiKey instance);
    partial void UpdateApiKey(ApiKey instance);
    partial void DeleteApiKey(ApiKey instance);
    partial void InsertApiUsageDaily(ApiUsageDaily instance);
    partial void UpdateApiUsageDaily(ApiUsageDaily instance);
    partial void DeleteApiUsageDaily(ApiUsageDaily instance);
    partial void InsertApiUsageLog(ApiUsageLog instance);
    partial void UpdateApiUsageLog(ApiUsageLog instance);
    partial void DeleteApiUsageLog(ApiUsageLog instance);
    partial void InsertClientCredential(ClientCredential instance);
    partial void UpdateClientCredential(ClientCredential instance);
    partial void DeleteClientCredential(ClientCredential instance);
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    partial void InsertPaymentProfile(PaymentProfile instance);
    partial void UpdatePaymentProfile(PaymentProfile instance);
    partial void DeletePaymentProfile(PaymentProfile instance);
    partial void InsertPlan(Plan instance);
    partial void UpdatePlan(Plan instance);
    partial void DeletePlan(Plan instance);
    partial void InsertSubscription(Subscription instance);
    partial void UpdateSubscription(Subscription instance);
    partial void DeleteSubscription(Subscription instance);
    #endregion
		
		public AutoDealerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoDealerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoDealerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoDealerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ApiKey> ApiKeys
		{
			get
			{
				return this.GetTable<ApiKey>();
			}
		}
		
		public System.Data.Linq.Table<ApiUsageDaily> ApiUsageDailies
		{
			get
			{
				return this.GetTable<ApiUsageDaily>();
			}
		}
		
		public System.Data.Linq.Table<ApiUsageLog> ApiUsageLogs
		{
			get
			{
				return this.GetTable<ApiUsageLog>();
			}
		}
		
		public System.Data.Linq.Table<ClientCredential> ClientCredentials
		{
			get
			{
				return this.GetTable<ClientCredential>();
			}
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		public System.Data.Linq.Table<PaymentProfile> PaymentProfiles
		{
			get
			{
				return this.GetTable<PaymentProfile>();
			}
		}
		
		public System.Data.Linq.Table<Plan> Plans
		{
			get
			{
				return this.GetTable<Plan>();
			}
		}
		
		public System.Data.Linq.Table<Subscription> Subscriptions
		{
			get
			{
				return this.GetTable<Subscription>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApiKeys")]
	public partial class ApiKey : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ApiKeyId;
		
		private long _ClientId;
		
		private long _SubscriptionId;
		
		private string _KeyId;
		
		private System.Data.Linq.Binary _SecretHash;
		
		private string _KeyPrefix;
		
		private string _Name;
		
		private string _Scopes;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _LastUsedUtc;
		
		private System.Nullable<System.DateTime> _ExpiresUtc;
		
		private System.Nullable<System.DateTime> _RevokedUtc;
		
		private System.DateTime _CreatedUtc;
		
		private EntityRef<Client> _Client;
		
		private EntityRef<Subscription> _Subscription;
		
		private EntitySet<ApiUsageLog> _ApiUsageLogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApiKeyIdChanging(long value);
    partial void OnApiKeyIdChanged();
    partial void OnClientIdChanging(long value);
    partial void OnClientIdChanged();
    partial void OnSubscriptionIdChanging(long value);
    partial void OnSubscriptionIdChanged();
    partial void OnKeyIdChanging(string value);
    partial void OnKeyIdChanged();
    partial void OnSecretHashChanging(System.Data.Linq.Binary value);
    partial void OnSecretHashChanged();
    partial void OnKeyPrefixChanging(string value);
    partial void OnKeyPrefixChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnScopesChanging(string value);
    partial void OnScopesChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnLastUsedUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUsedUtcChanged();
    partial void OnExpiresUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiresUtcChanged();
    partial void OnRevokedUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnRevokedUtcChanged();
    partial void OnCreatedUtcChanging(System.DateTime value);
    partial void OnCreatedUtcChanged();
    #endregion
		
		public ApiKey()
		{
			this._Client = default(EntityRef<Client>);
			this._Subscription = default(EntityRef<Subscription>);
			this._ApiUsageLogs = new EntitySet<ApiUsageLog>(new Action<ApiUsageLog>(this.attach_ApiUsageLogs), new Action<ApiUsageLog>(this.detach_ApiUsageLogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApiKeyId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ApiKeyId
		{
			get
			{
				return this._ApiKeyId;
			}
			set
			{
				if ((this._ApiKeyId != value))
				{
					this.OnApiKeyIdChanging(value);
					this.SendPropertyChanging();
					this._ApiKeyId = value;
					this.SendPropertyChanged("ApiKeyId");
					this.OnApiKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="BigInt NOT NULL")]
		public long ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", DbType="BigInt NOT NULL")]
		public long SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					if (this._Subscription.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("SubscriptionId");
					this.OnSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecretHash", DbType="Binary(32) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary SecretHash
		{
			get
			{
				return this._SecretHash;
			}
			set
			{
				if ((this._SecretHash != value))
				{
					this.OnSecretHashChanging(value);
					this.SendPropertyChanging();
					this._SecretHash = value;
					this.SendPropertyChanged("SecretHash");
					this.OnSecretHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyPrefix", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string KeyPrefix
		{
			get
			{
				return this._KeyPrefix;
			}
			set
			{
				if ((this._KeyPrefix != value))
				{
					this.OnKeyPrefixChanging(value);
					this.SendPropertyChanging();
					this._KeyPrefix = value;
					this.SendPropertyChanged("KeyPrefix");
					this.OnKeyPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scopes", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Scopes
		{
			get
			{
				return this._Scopes;
			}
			set
			{
				if ((this._Scopes != value))
				{
					this.OnScopesChanging(value);
					this.SendPropertyChanging();
					this._Scopes = value;
					this.SendPropertyChanged("Scopes");
					this.OnScopesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUsedUtc", DbType="DateTime2(3)")]
		public System.Nullable<System.DateTime> LastUsedUtc
		{
			get
			{
				return this._LastUsedUtc;
			}
			set
			{
				if ((this._LastUsedUtc != value))
				{
					this.OnLastUsedUtcChanging(value);
					this.SendPropertyChanging();
					this._LastUsedUtc = value;
					this.SendPropertyChanged("LastUsedUtc");
					this.OnLastUsedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiresUtc", DbType="DateTime2(3)")]
		public System.Nullable<System.DateTime> ExpiresUtc
		{
			get
			{
				return this._ExpiresUtc;
			}
			set
			{
				if ((this._ExpiresUtc != value))
				{
					this.OnExpiresUtcChanging(value);
					this.SendPropertyChanging();
					this._ExpiresUtc = value;
					this.SendPropertyChanged("ExpiresUtc");
					this.OnExpiresUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RevokedUtc", DbType="DateTime2(3)")]
		public System.Nullable<System.DateTime> RevokedUtc
		{
			get
			{
				return this._RevokedUtc;
			}
			set
			{
				if ((this._RevokedUtc != value))
				{
					this.OnRevokedUtcChanging(value);
					this.SendPropertyChanging();
					this._RevokedUtc = value;
					this.SendPropertyChanged("RevokedUtc");
					this.OnRevokedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime CreatedUtc
		{
			get
			{
				return this._CreatedUtc;
			}
			set
			{
				if ((this._CreatedUtc != value))
				{
					this.OnCreatedUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedUtc = value;
					this.SendPropertyChanged("CreatedUtc");
					this.OnCreatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiKeys_Client", Storage="_Client", ThisKey="ClientId", OtherKey="ClientId", IsForeignKey=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.ApiKeys.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.ApiKeys.Add(this);
						this._ClientId = value.ClientId;
					}
					else
					{
						this._ClientId = default(long);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiKeys_Subscription", Storage="_Subscription", ThisKey="SubscriptionId", OtherKey="SubscriptionId", IsForeignKey=true)]
		public Subscription Subscription
		{
			get
			{
				return this._Subscription.Entity;
			}
			set
			{
				Subscription previousValue = this._Subscription.Entity;
				if (((previousValue != value) 
							|| (this._Subscription.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subscription.Entity = null;
						previousValue.ApiKeys.Remove(this);
					}
					this._Subscription.Entity = value;
					if ((value != null))
					{
						value.ApiKeys.Add(this);
						this._SubscriptionId = value.SubscriptionId;
					}
					else
					{
						this._SubscriptionId = default(long);
					}
					this.SendPropertyChanged("Subscription");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageLog_Key", Storage="_ApiUsageLogs", ThisKey="ApiKeyId", OtherKey="ApiKeyId", DeleteRule="NO ACTION")]
		public EntitySet<ApiUsageLog> ApiUsageLogs
		{
			get
			{
				return this._ApiUsageLogs;
			}
			set
			{
				this._ApiUsageLogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ApiUsageLogs(ApiUsageLog entity)
		{
			this.SendPropertyChanging();
			entity.ApiKey = this;
		}
		
		private void detach_ApiUsageLogs(ApiUsageLog entity)
		{
			this.SendPropertyChanging();
			entity.ApiKey = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApiUsageDaily")]
	public partial class ApiUsageDaily : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _UsageDate;
		
		private long _ClientId;
		
		private long _SubscriptionId;
		
		private int _RequestCount;
		
		private int _ErrorCount;
		
		private long _TotalDurationMs;
		
		private EntityRef<Client> _Client;
		
		private EntityRef<Subscription> _Subscription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsageDateChanging(System.DateTime value);
    partial void OnUsageDateChanged();
    partial void OnClientIdChanging(long value);
    partial void OnClientIdChanged();
    partial void OnSubscriptionIdChanging(long value);
    partial void OnSubscriptionIdChanged();
    partial void OnRequestCountChanging(int value);
    partial void OnRequestCountChanged();
    partial void OnErrorCountChanging(int value);
    partial void OnErrorCountChanged();
    partial void OnTotalDurationMsChanging(long value);
    partial void OnTotalDurationMsChanged();
    #endregion
		
		public ApiUsageDaily()
		{
			this._Client = default(EntityRef<Client>);
			this._Subscription = default(EntityRef<Subscription>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsageDate", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime UsageDate
		{
			get
			{
				return this._UsageDate;
			}
			set
			{
				if ((this._UsageDate != value))
				{
					this.OnUsageDateChanging(value);
					this.SendPropertyChanging();
					this._UsageDate = value;
					this.SendPropertyChanged("UsageDate");
					this.OnUsageDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="BigInt NOT NULL")]
		public long ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					if (this._Subscription.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("SubscriptionId");
					this.OnSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestCount", DbType="Int NOT NULL")]
		public int RequestCount
		{
			get
			{
				return this._RequestCount;
			}
			set
			{
				if ((this._RequestCount != value))
				{
					this.OnRequestCountChanging(value);
					this.SendPropertyChanging();
					this._RequestCount = value;
					this.SendPropertyChanged("RequestCount");
					this.OnRequestCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCount", DbType="Int NOT NULL")]
		public int ErrorCount
		{
			get
			{
				return this._ErrorCount;
			}
			set
			{
				if ((this._ErrorCount != value))
				{
					this.OnErrorCountChanging(value);
					this.SendPropertyChanging();
					this._ErrorCount = value;
					this.SendPropertyChanged("ErrorCount");
					this.OnErrorCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDurationMs", DbType="BigInt NOT NULL")]
		public long TotalDurationMs
		{
			get
			{
				return this._TotalDurationMs;
			}
			set
			{
				if ((this._TotalDurationMs != value))
				{
					this.OnTotalDurationMsChanging(value);
					this.SendPropertyChanging();
					this._TotalDurationMs = value;
					this.SendPropertyChanged("TotalDurationMs");
					this.OnTotalDurationMsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageDaily_Client", Storage="_Client", ThisKey="ClientId", OtherKey="ClientId", IsForeignKey=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.ApiUsageDailies.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.ApiUsageDailies.Add(this);
						this._ClientId = value.ClientId;
					}
					else
					{
						this._ClientId = default(long);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageDaily_Subscription", Storage="_Subscription", ThisKey="SubscriptionId", OtherKey="SubscriptionId", IsForeignKey=true)]
		public Subscription Subscription
		{
			get
			{
				return this._Subscription.Entity;
			}
			set
			{
				Subscription previousValue = this._Subscription.Entity;
				if (((previousValue != value) 
							|| (this._Subscription.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subscription.Entity = null;
						previousValue.ApiUsageDailies.Remove(this);
					}
					this._Subscription.Entity = value;
					if ((value != null))
					{
						value.ApiUsageDailies.Add(this);
						this._SubscriptionId = value.SubscriptionId;
					}
					else
					{
						this._SubscriptionId = default(long);
					}
					this.SendPropertyChanged("Subscription");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApiUsageLog")]
	public partial class ApiUsageLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _RequestId;
		
		private long _ApiKeyId;
		
		private long _ClientId;
		
		private long _SubscriptionId;
		
		private string _Endpoint;
		
		private string _HttpMethod;
		
		private System.Nullable<short> _StatusCode;
		
		private System.Nullable<int> _DurationMs;
		
		private string _IpAddress;
		
		private string _UserAgent;
		
		private System.DateTime _RequestedUtc;
		
		private System.Nullable<System.DateTime> _CompletedUtc;
		
		private EntityRef<Client> _Client;
		
		private EntityRef<ApiKey> _ApiKey;
		
		private EntityRef<Subscription> _Subscription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRequestIdChanging(System.Guid value);
    partial void OnRequestIdChanged();
    partial void OnApiKeyIdChanging(long value);
    partial void OnApiKeyIdChanged();
    partial void OnClientIdChanging(long value);
    partial void OnClientIdChanged();
    partial void OnSubscriptionIdChanging(long value);
    partial void OnSubscriptionIdChanged();
    partial void OnEndpointChanging(string value);
    partial void OnEndpointChanged();
    partial void OnHttpMethodChanging(string value);
    partial void OnHttpMethodChanged();
    partial void OnStatusCodeChanging(System.Nullable<short> value);
    partial void OnStatusCodeChanged();
    partial void OnDurationMsChanging(System.Nullable<int> value);
    partial void OnDurationMsChanged();
    partial void OnIpAddressChanging(string value);
    partial void OnIpAddressChanged();
    partial void OnUserAgentChanging(string value);
    partial void OnUserAgentChanged();
    partial void OnRequestedUtcChanging(System.DateTime value);
    partial void OnRequestedUtcChanged();
    partial void OnCompletedUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCompletedUtcChanged();
    #endregion
		
		public ApiUsageLog()
		{
			this._Client = default(EntityRef<Client>);
			this._ApiKey = default(EntityRef<ApiKey>);
			this._Subscription = default(EntityRef<Subscription>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RequestId
		{
			get
			{
				return this._RequestId;
			}
			set
			{
				if ((this._RequestId != value))
				{
					this.OnRequestIdChanging(value);
					this.SendPropertyChanging();
					this._RequestId = value;
					this.SendPropertyChanged("RequestId");
					this.OnRequestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApiKeyId", DbType="BigInt NOT NULL")]
		public long ApiKeyId
		{
			get
			{
				return this._ApiKeyId;
			}
			set
			{
				if ((this._ApiKeyId != value))
				{
					if (this._ApiKey.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnApiKeyIdChanging(value);
					this.SendPropertyChanging();
					this._ApiKeyId = value;
					this.SendPropertyChanged("ApiKeyId");
					this.OnApiKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="BigInt NOT NULL")]
		public long ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", DbType="BigInt NOT NULL")]
		public long SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					if (this._Subscription.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("SubscriptionId");
					this.OnSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endpoint", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Endpoint
		{
			get
			{
				return this._Endpoint;
			}
			set
			{
				if ((this._Endpoint != value))
				{
					this.OnEndpointChanging(value);
					this.SendPropertyChanging();
					this._Endpoint = value;
					this.SendPropertyChanged("Endpoint");
					this.OnEndpointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HttpMethod", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string HttpMethod
		{
			get
			{
				return this._HttpMethod;
			}
			set
			{
				if ((this._HttpMethod != value))
				{
					this.OnHttpMethodChanging(value);
					this.SendPropertyChanging();
					this._HttpMethod = value;
					this.SendPropertyChanged("HttpMethod");
					this.OnHttpMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusCode", DbType="SmallInt")]
		public System.Nullable<short> StatusCode
		{
			get
			{
				return this._StatusCode;
			}
			set
			{
				if ((this._StatusCode != value))
				{
					this.OnStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._StatusCode = value;
					this.SendPropertyChanged("StatusCode");
					this.OnStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationMs", DbType="Int")]
		public System.Nullable<int> DurationMs
		{
			get
			{
				return this._DurationMs;
			}
			set
			{
				if ((this._DurationMs != value))
				{
					this.OnDurationMsChanging(value);
					this.SendPropertyChanging();
					this._DurationMs = value;
					this.SendPropertyChanged("DurationMs");
					this.OnDurationMsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpAddress", DbType="VarChar(64)")]
		public string IpAddress
		{
			get
			{
				return this._IpAddress;
			}
			set
			{
				if ((this._IpAddress != value))
				{
					this.OnIpAddressChanging(value);
					this.SendPropertyChanging();
					this._IpAddress = value;
					this.SendPropertyChanged("IpAddress");
					this.OnIpAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAgent", DbType="NVarChar(300)")]
		public string UserAgent
		{
			get
			{
				return this._UserAgent;
			}
			set
			{
				if ((this._UserAgent != value))
				{
					this.OnUserAgentChanging(value);
					this.SendPropertyChanging();
					this._UserAgent = value;
					this.SendPropertyChanged("UserAgent");
					this.OnUserAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestedUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime RequestedUtc
		{
			get
			{
				return this._RequestedUtc;
			}
			set
			{
				if ((this._RequestedUtc != value))
				{
					this.OnRequestedUtcChanging(value);
					this.SendPropertyChanging();
					this._RequestedUtc = value;
					this.SendPropertyChanged("RequestedUtc");
					this.OnRequestedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletedUtc", DbType="DateTime2(3)")]
		public System.Nullable<System.DateTime> CompletedUtc
		{
			get
			{
				return this._CompletedUtc;
			}
			set
			{
				if ((this._CompletedUtc != value))
				{
					this.OnCompletedUtcChanging(value);
					this.SendPropertyChanging();
					this._CompletedUtc = value;
					this.SendPropertyChanged("CompletedUtc");
					this.OnCompletedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageLog_Client", Storage="_Client", ThisKey="ClientId", OtherKey="ClientId", IsForeignKey=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.ApiUsageLogs.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.ApiUsageLogs.Add(this);
						this._ClientId = value.ClientId;
					}
					else
					{
						this._ClientId = default(long);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageLog_Key", Storage="_ApiKey", ThisKey="ApiKeyId", OtherKey="ApiKeyId", IsForeignKey=true)]
		public ApiKey ApiKey
		{
			get
			{
				return this._ApiKey.Entity;
			}
			set
			{
				ApiKey previousValue = this._ApiKey.Entity;
				if (((previousValue != value) 
							|| (this._ApiKey.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ApiKey.Entity = null;
						previousValue.ApiUsageLogs.Remove(this);
					}
					this._ApiKey.Entity = value;
					if ((value != null))
					{
						value.ApiUsageLogs.Add(this);
						this._ApiKeyId = value.ApiKeyId;
					}
					else
					{
						this._ApiKeyId = default(long);
					}
					this.SendPropertyChanged("ApiKey");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageLog_Subscription", Storage="_Subscription", ThisKey="SubscriptionId", OtherKey="SubscriptionId", IsForeignKey=true)]
		public Subscription Subscription
		{
			get
			{
				return this._Subscription.Entity;
			}
			set
			{
				Subscription previousValue = this._Subscription.Entity;
				if (((previousValue != value) 
							|| (this._Subscription.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subscription.Entity = null;
						previousValue.ApiUsageLogs.Remove(this);
					}
					this._Subscription.Entity = value;
					if ((value != null))
					{
						value.ApiUsageLogs.Add(this);
						this._SubscriptionId = value.SubscriptionId;
					}
					else
					{
						this._SubscriptionId = default(long);
					}
					this.SendPropertyChanged("Subscription");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientCredentials")]
	public partial class ClientCredential : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ClientId;
		
		private System.Data.Linq.Binary _PasswordHash;
		
		private System.Data.Linq.Binary _PasswordSalt;
		
		private int _PasswordIterations;
		
		private string _PasswordAlgorithm;
		
		private System.DateTime _PasswordChangedUtc;
		
		private int _FailedLoginCount;
		
		private System.Nullable<System.DateTime> _LockedUntilUtc;
		
		private EntityRef<Client> _Client;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClientIdChanging(long value);
    partial void OnClientIdChanged();
    partial void OnPasswordHashChanging(System.Data.Linq.Binary value);
    partial void OnPasswordHashChanged();
    partial void OnPasswordSaltChanging(System.Data.Linq.Binary value);
    partial void OnPasswordSaltChanged();
    partial void OnPasswordIterationsChanging(int value);
    partial void OnPasswordIterationsChanged();
    partial void OnPasswordAlgorithmChanging(string value);
    partial void OnPasswordAlgorithmChanged();
    partial void OnPasswordChangedUtcChanging(System.DateTime value);
    partial void OnPasswordChangedUtcChanged();
    partial void OnFailedLoginCountChanging(int value);
    partial void OnFailedLoginCountChanged();
    partial void OnLockedUntilUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnLockedUntilUtcChanged();
    #endregion
		
		public ClientCredential()
		{
			this._Client = default(EntityRef<Client>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="VarBinary(64) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="VarBinary(64) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordIterations", DbType="Int NOT NULL")]
		public int PasswordIterations
		{
			get
			{
				return this._PasswordIterations;
			}
			set
			{
				if ((this._PasswordIterations != value))
				{
					this.OnPasswordIterationsChanging(value);
					this.SendPropertyChanging();
					this._PasswordIterations = value;
					this.SendPropertyChanged("PasswordIterations");
					this.OnPasswordIterationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAlgorithm", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string PasswordAlgorithm
		{
			get
			{
				return this._PasswordAlgorithm;
			}
			set
			{
				if ((this._PasswordAlgorithm != value))
				{
					this.OnPasswordAlgorithmChanging(value);
					this.SendPropertyChanging();
					this._PasswordAlgorithm = value;
					this.SendPropertyChanged("PasswordAlgorithm");
					this.OnPasswordAlgorithmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordChangedUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime PasswordChangedUtc
		{
			get
			{
				return this._PasswordChangedUtc;
			}
			set
			{
				if ((this._PasswordChangedUtc != value))
				{
					this.OnPasswordChangedUtcChanging(value);
					this.SendPropertyChanging();
					this._PasswordChangedUtc = value;
					this.SendPropertyChanged("PasswordChangedUtc");
					this.OnPasswordChangedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedLoginCount", DbType="Int NOT NULL")]
		public int FailedLoginCount
		{
			get
			{
				return this._FailedLoginCount;
			}
			set
			{
				if ((this._FailedLoginCount != value))
				{
					this.OnFailedLoginCountChanging(value);
					this.SendPropertyChanging();
					this._FailedLoginCount = value;
					this.SendPropertyChanged("FailedLoginCount");
					this.OnFailedLoginCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockedUntilUtc", DbType="DateTime2(3)")]
		public System.Nullable<System.DateTime> LockedUntilUtc
		{
			get
			{
				return this._LockedUntilUtc;
			}
			set
			{
				if ((this._LockedUntilUtc != value))
				{
					this.OnLockedUntilUtcChanging(value);
					this.SendPropertyChanging();
					this._LockedUntilUtc = value;
					this.SendPropertyChanged("LockedUntilUtc");
					this.OnLockedUntilUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ClientCredentials_Client", Storage="_Client", ThisKey="ClientId", OtherKey="ClientId", IsForeignKey=true, DeleteOnNull=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.ClientCredential = null;
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.ClientCredential = this;
						this._ClientId = value.ClientId;
					}
					else
					{
						this._ClientId = default(long);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clients")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ClientId;
		
		private string _ClientNumber;
		
		private string _BusinessName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _Phone;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _EmailVerifiedUtc;
		
		private System.DateTime _CreatedUtc;
		
		private System.DateTime _UpdatedUtc;
		
		private System.Data.Linq.Binary _RowVersion;
		
		private EntitySet<ApiKey> _ApiKeys;
		
		private EntitySet<ApiUsageDaily> _ApiUsageDailies;
		
		private EntitySet<ApiUsageLog> _ApiUsageLogs;
		
		private EntityRef<ClientCredential> _ClientCredential;
		
		private EntitySet<PaymentProfile> _PaymentProfiles;
		
		private EntitySet<Subscription> _Subscriptions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClientIdChanging(long value);
    partial void OnClientIdChanged();
    partial void OnClientNumberChanging(string value);
    partial void OnClientNumberChanged();
    partial void OnBusinessNameChanging(string value);
    partial void OnBusinessNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnEmailVerifiedUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnEmailVerifiedUtcChanged();
    partial void OnCreatedUtcChanging(System.DateTime value);
    partial void OnCreatedUtcChanged();
    partial void OnUpdatedUtcChanging(System.DateTime value);
    partial void OnUpdatedUtcChanged();
    partial void OnRowVersionChanging(System.Data.Linq.Binary value);
    partial void OnRowVersionChanged();
    #endregion
		
		public Client()
		{
			this._ApiKeys = new EntitySet<ApiKey>(new Action<ApiKey>(this.attach_ApiKeys), new Action<ApiKey>(this.detach_ApiKeys));
			this._ApiUsageDailies = new EntitySet<ApiUsageDaily>(new Action<ApiUsageDaily>(this.attach_ApiUsageDailies), new Action<ApiUsageDaily>(this.detach_ApiUsageDailies));
			this._ApiUsageLogs = new EntitySet<ApiUsageLog>(new Action<ApiUsageLog>(this.attach_ApiUsageLogs), new Action<ApiUsageLog>(this.detach_ApiUsageLogs));
			this._ClientCredential = default(EntityRef<ClientCredential>);
			this._PaymentProfiles = new EntitySet<PaymentProfile>(new Action<PaymentProfile>(this.attach_PaymentProfiles), new Action<PaymentProfile>(this.detach_PaymentProfiles));
			this._Subscriptions = new EntitySet<Subscription>(new Action<Subscription>(this.attach_Subscriptions), new Action<Subscription>(this.detach_Subscriptions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientNumber", DbType="VarChar(32) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ClientNumber
		{
			get
			{
				return this._ClientNumber;
			}
			set
			{
				if ((this._ClientNumber != value))
				{
					this.OnClientNumberChanging(value);
					this.SendPropertyChanging();
					this._ClientNumber = value;
					this.SendPropertyChanged("ClientNumber");
					this.OnClientNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessName", DbType="NVarChar(160) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BusinessName
		{
			get
			{
				return this._BusinessName;
			}
			set
			{
				if ((this._BusinessName != value))
				{
					this.OnBusinessNameChanging(value);
					this.SendPropertyChanging();
					this._BusinessName = value;
					this.SendPropertyChanged("BusinessName");
					this.OnBusinessNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(80) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(80) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(254) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(32)", UpdateCheck=UpdateCheck.Never)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailVerifiedUtc", DbType="DateTime2(3)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> EmailVerifiedUtc
		{
			get
			{
				return this._EmailVerifiedUtc;
			}
			set
			{
				if ((this._EmailVerifiedUtc != value))
				{
					this.OnEmailVerifiedUtcChanging(value);
					this.SendPropertyChanging();
					this._EmailVerifiedUtc = value;
					this.SendPropertyChanged("EmailVerifiedUtc");
					this.OnEmailVerifiedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUtc", DbType="DateTime2(3) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime CreatedUtc
		{
			get
			{
				return this._CreatedUtc;
			}
			set
			{
				if ((this._CreatedUtc != value))
				{
					this.OnCreatedUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedUtc = value;
					this.SendPropertyChanged("CreatedUtc");
					this.OnCreatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedUtc", DbType="DateTime2(3) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime UpdatedUtc
		{
			get
			{
				return this._UpdatedUtc;
			}
			set
			{
				if ((this._UpdatedUtc != value))
				{
					this.OnUpdatedUtcChanging(value);
					this.SendPropertyChanging();
					this._UpdatedUtc = value;
					this.SendPropertyChanged("UpdatedUtc");
					this.OnUpdatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowVersion", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary RowVersion
		{
			get
			{
				return this._RowVersion;
			}
			set
			{
				if ((this._RowVersion != value))
				{
					this.OnRowVersionChanging(value);
					this.SendPropertyChanging();
					this._RowVersion = value;
					this.SendPropertyChanged("RowVersion");
					this.OnRowVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiKeys_Client", Storage="_ApiKeys", ThisKey="ClientId", OtherKey="ClientId", DeleteRule="NO ACTION")]
		public EntitySet<ApiKey> ApiKeys
		{
			get
			{
				return this._ApiKeys;
			}
			set
			{
				this._ApiKeys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageDaily_Client", Storage="_ApiUsageDailies", ThisKey="ClientId", OtherKey="ClientId", DeleteRule="NO ACTION")]
		public EntitySet<ApiUsageDaily> ApiUsageDailies
		{
			get
			{
				return this._ApiUsageDailies;
			}
			set
			{
				this._ApiUsageDailies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageLog_Client", Storage="_ApiUsageLogs", ThisKey="ClientId", OtherKey="ClientId", DeleteRule="NO ACTION")]
		public EntitySet<ApiUsageLog> ApiUsageLogs
		{
			get
			{
				return this._ApiUsageLogs;
			}
			set
			{
				this._ApiUsageLogs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ClientCredentials_Client", Storage="_ClientCredential", ThisKey="ClientId", OtherKey="ClientId", IsUnique=true, IsForeignKey=false, DeleteRule="CASCADE")]
		public ClientCredential ClientCredential
		{
			get
			{
				return this._ClientCredential.Entity;
			}
			set
			{
				ClientCredential previousValue = this._ClientCredential.Entity;
				if (((previousValue != value) 
							|| (this._ClientCredential.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientCredential.Entity = null;
						previousValue.Client = null;
					}
					this._ClientCredential.Entity = value;
					if ((value != null))
					{
						value.Client = this;
					}
					this.SendPropertyChanged("ClientCredential");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_PaymentProfiles_Client", Storage="_PaymentProfiles", ThisKey="ClientId", OtherKey="ClientId", DeleteRule="CASCADE")]
		public EntitySet<PaymentProfile> PaymentProfiles
		{
			get
			{
				return this._PaymentProfiles;
			}
			set
			{
				this._PaymentProfiles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Subscriptions_Client", Storage="_Subscriptions", ThisKey="ClientId", OtherKey="ClientId", DeleteRule="NO ACTION")]
		public EntitySet<Subscription> Subscriptions
		{
			get
			{
				return this._Subscriptions;
			}
			set
			{
				this._Subscriptions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ApiKeys(ApiKey entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_ApiKeys(ApiKey entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
		
		private void attach_ApiUsageDailies(ApiUsageDaily entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_ApiUsageDailies(ApiUsageDaily entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
		
		private void attach_ApiUsageLogs(ApiUsageLog entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_ApiUsageLogs(ApiUsageLog entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
		
		private void attach_PaymentProfiles(PaymentProfile entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_PaymentProfiles(PaymentProfile entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
		
		private void attach_Subscriptions(Subscription entity)
		{
			this.SendPropertyChanging();
			entity.Client = this;
		}
		
		private void detach_Subscriptions(Subscription entity)
		{
			this.SendPropertyChanging();
			entity.Client = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentProfiles")]
	public partial class PaymentProfile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PaymentProfileId;
		
		private long _ClientId;
		
		private string _Provider;
		
		private string _ProviderCustomerId;
		
		private string _ProviderPaymentMethodId;
		
		private string _CardBrand;
		
		private string _CardLast4;
		
		private System.Nullable<byte> _ExpMonth;
		
		private System.Nullable<short> _ExpYear;
		
		private bool _IsDefault;
		
		private System.DateTime _CreatedUtc;
		
		private EntityRef<Client> _Client;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaymentProfileIdChanging(long value);
    partial void OnPaymentProfileIdChanged();
    partial void OnClientIdChanging(long value);
    partial void OnClientIdChanged();
    partial void OnProviderChanging(string value);
    partial void OnProviderChanged();
    partial void OnProviderCustomerIdChanging(string value);
    partial void OnProviderCustomerIdChanged();
    partial void OnProviderPaymentMethodIdChanging(string value);
    partial void OnProviderPaymentMethodIdChanged();
    partial void OnCardBrandChanging(string value);
    partial void OnCardBrandChanged();
    partial void OnCardLast4Changing(string value);
    partial void OnCardLast4Changed();
    partial void OnExpMonthChanging(System.Nullable<byte> value);
    partial void OnExpMonthChanged();
    partial void OnExpYearChanging(System.Nullable<short> value);
    partial void OnExpYearChanged();
    partial void OnIsDefaultChanging(bool value);
    partial void OnIsDefaultChanged();
    partial void OnCreatedUtcChanging(System.DateTime value);
    partial void OnCreatedUtcChanged();
    #endregion
		
		public PaymentProfile()
		{
			this._Client = default(EntityRef<Client>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentProfileId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PaymentProfileId
		{
			get
			{
				return this._PaymentProfileId;
			}
			set
			{
				if ((this._PaymentProfileId != value))
				{
					this.OnPaymentProfileIdChanging(value);
					this.SendPropertyChanging();
					this._PaymentProfileId = value;
					this.SendPropertyChanged("PaymentProfileId");
					this.OnPaymentProfileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="BigInt NOT NULL")]
		public long ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Provider
		{
			get
			{
				return this._Provider;
			}
			set
			{
				if ((this._Provider != value))
				{
					this.OnProviderChanging(value);
					this.SendPropertyChanging();
					this._Provider = value;
					this.SendPropertyChanged("Provider");
					this.OnProviderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderCustomerId", DbType="NVarChar(200)")]
		public string ProviderCustomerId
		{
			get
			{
				return this._ProviderCustomerId;
			}
			set
			{
				if ((this._ProviderCustomerId != value))
				{
					this.OnProviderCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._ProviderCustomerId = value;
					this.SendPropertyChanged("ProviderCustomerId");
					this.OnProviderCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderPaymentMethodId", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ProviderPaymentMethodId
		{
			get
			{
				return this._ProviderPaymentMethodId;
			}
			set
			{
				if ((this._ProviderPaymentMethodId != value))
				{
					this.OnProviderPaymentMethodIdChanging(value);
					this.SendPropertyChanging();
					this._ProviderPaymentMethodId = value;
					this.SendPropertyChanged("ProviderPaymentMethodId");
					this.OnProviderPaymentMethodIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardBrand", DbType="VarChar(30)")]
		public string CardBrand
		{
			get
			{
				return this._CardBrand;
			}
			set
			{
				if ((this._CardBrand != value))
				{
					this.OnCardBrandChanging(value);
					this.SendPropertyChanging();
					this._CardBrand = value;
					this.SendPropertyChanged("CardBrand");
					this.OnCardBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardLast4", DbType="Char(4)")]
		public string CardLast4
		{
			get
			{
				return this._CardLast4;
			}
			set
			{
				if ((this._CardLast4 != value))
				{
					this.OnCardLast4Changing(value);
					this.SendPropertyChanging();
					this._CardLast4 = value;
					this.SendPropertyChanged("CardLast4");
					this.OnCardLast4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpMonth", DbType="TinyInt")]
		public System.Nullable<byte> ExpMonth
		{
			get
			{
				return this._ExpMonth;
			}
			set
			{
				if ((this._ExpMonth != value))
				{
					this.OnExpMonthChanging(value);
					this.SendPropertyChanging();
					this._ExpMonth = value;
					this.SendPropertyChanged("ExpMonth");
					this.OnExpMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpYear", DbType="SmallInt")]
		public System.Nullable<short> ExpYear
		{
			get
			{
				return this._ExpYear;
			}
			set
			{
				if ((this._ExpYear != value))
				{
					this.OnExpYearChanging(value);
					this.SendPropertyChanging();
					this._ExpYear = value;
					this.SendPropertyChanged("ExpYear");
					this.OnExpYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefault", DbType="Bit NOT NULL")]
		public bool IsDefault
		{
			get
			{
				return this._IsDefault;
			}
			set
			{
				if ((this._IsDefault != value))
				{
					this.OnIsDefaultChanging(value);
					this.SendPropertyChanging();
					this._IsDefault = value;
					this.SendPropertyChanged("IsDefault");
					this.OnIsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime CreatedUtc
		{
			get
			{
				return this._CreatedUtc;
			}
			set
			{
				if ((this._CreatedUtc != value))
				{
					this.OnCreatedUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedUtc = value;
					this.SendPropertyChanged("CreatedUtc");
					this.OnCreatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_PaymentProfiles_Client", Storage="_Client", ThisKey="ClientId", OtherKey="ClientId", IsForeignKey=true, DeleteOnNull=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.PaymentProfiles.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.PaymentProfiles.Add(this);
						this._ClientId = value.ClientId;
					}
					else
					{
						this._ClientId = default(long);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Plans")]
	public partial class Plan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PlanId;
		
		private string _PlanCode;
		
		private string _DisplayName;
		
		private System.Nullable<decimal> _MonthlyPrice;
		
		private int _MonthlyRequestQuota;
		
		private short _MaxApiKeys;
		
		private bool _IsActive;
		
		private System.DateTime _CreatedUtc;
		
		private EntitySet<Subscription> _Subscriptions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlanIdChanging(int value);
    partial void OnPlanIdChanged();
    partial void OnPlanCodeChanging(string value);
    partial void OnPlanCodeChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnMonthlyPriceChanging(System.Nullable<decimal> value);
    partial void OnMonthlyPriceChanged();
    partial void OnMonthlyRequestQuotaChanging(int value);
    partial void OnMonthlyRequestQuotaChanged();
    partial void OnMaxApiKeysChanging(short value);
    partial void OnMaxApiKeysChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnCreatedUtcChanging(System.DateTime value);
    partial void OnCreatedUtcChanged();
    #endregion
		
		public Plan()
		{
			this._Subscriptions = new EntitySet<Subscription>(new Action<Subscription>(this.attach_Subscriptions), new Action<Subscription>(this.detach_Subscriptions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PlanId
		{
			get
			{
				return this._PlanId;
			}
			set
			{
				if ((this._PlanId != value))
				{
					this.OnPlanIdChanging(value);
					this.SendPropertyChanging();
					this._PlanId = value;
					this.SendPropertyChanged("PlanId");
					this.OnPlanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanCode", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string PlanCode
		{
			get
			{
				return this._PlanCode;
			}
			set
			{
				if ((this._PlanCode != value))
				{
					this.OnPlanCodeChanging(value);
					this.SendPropertyChanging();
					this._PlanCode = value;
					this.SendPropertyChanged("PlanCode");
					this.OnPlanCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthlyPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MonthlyPrice
		{
			get
			{
				return this._MonthlyPrice;
			}
			set
			{
				if ((this._MonthlyPrice != value))
				{
					this.OnMonthlyPriceChanging(value);
					this.SendPropertyChanging();
					this._MonthlyPrice = value;
					this.SendPropertyChanged("MonthlyPrice");
					this.OnMonthlyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthlyRequestQuota", DbType="Int NOT NULL")]
		public int MonthlyRequestQuota
		{
			get
			{
				return this._MonthlyRequestQuota;
			}
			set
			{
				if ((this._MonthlyRequestQuota != value))
				{
					this.OnMonthlyRequestQuotaChanging(value);
					this.SendPropertyChanging();
					this._MonthlyRequestQuota = value;
					this.SendPropertyChanged("MonthlyRequestQuota");
					this.OnMonthlyRequestQuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxApiKeys", DbType="SmallInt NOT NULL")]
		public short MaxApiKeys
		{
			get
			{
				return this._MaxApiKeys;
			}
			set
			{
				if ((this._MaxApiKeys != value))
				{
					this.OnMaxApiKeysChanging(value);
					this.SendPropertyChanging();
					this._MaxApiKeys = value;
					this.SendPropertyChanged("MaxApiKeys");
					this.OnMaxApiKeysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime CreatedUtc
		{
			get
			{
				return this._CreatedUtc;
			}
			set
			{
				if ((this._CreatedUtc != value))
				{
					this.OnCreatedUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedUtc = value;
					this.SendPropertyChanged("CreatedUtc");
					this.OnCreatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Subscriptions_Plan", Storage="_Subscriptions", ThisKey="PlanId", OtherKey="PlanId", DeleteRule="NO ACTION")]
		public EntitySet<Subscription> Subscriptions
		{
			get
			{
				return this._Subscriptions;
			}
			set
			{
				this._Subscriptions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Subscriptions(Subscription entity)
		{
			this.SendPropertyChanging();
			entity.Plan = this;
		}
		
		private void detach_Subscriptions(Subscription entity)
		{
			this.SendPropertyChanging();
			entity.Plan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subscriptions")]
	public partial class Subscription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SubscriptionId;
		
		private long _ClientId;
		
		private int _PlanId;
		
		private string _Status;
		
		private System.DateTime _CurrentPeriodStartUtc;
		
		private System.DateTime _CurrentPeriodEndUtc;
		
		private bool _CancelAtPeriodEnd;
		
		private string _ProviderSubscriptionId;
		
		private System.DateTime _CreatedUtc;
		
		private System.DateTime _UpdatedUtc;
		
		private EntitySet<ApiKey> _ApiKeys;
		
		private EntitySet<ApiUsageDaily> _ApiUsageDailies;
		
		private EntitySet<ApiUsageLog> _ApiUsageLogs;
		
		private EntityRef<Client> _Client;
		
		private EntityRef<Plan> _Plan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubscriptionIdChanging(long value);
    partial void OnSubscriptionIdChanged();
    partial void OnClientIdChanging(long value);
    partial void OnClientIdChanged();
    partial void OnPlanIdChanging(int value);
    partial void OnPlanIdChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCurrentPeriodStartUtcChanging(System.DateTime value);
    partial void OnCurrentPeriodStartUtcChanged();
    partial void OnCurrentPeriodEndUtcChanging(System.DateTime value);
    partial void OnCurrentPeriodEndUtcChanged();
    partial void OnCancelAtPeriodEndChanging(bool value);
    partial void OnCancelAtPeriodEndChanged();
    partial void OnProviderSubscriptionIdChanging(string value);
    partial void OnProviderSubscriptionIdChanged();
    partial void OnCreatedUtcChanging(System.DateTime value);
    partial void OnCreatedUtcChanged();
    partial void OnUpdatedUtcChanging(System.DateTime value);
    partial void OnUpdatedUtcChanged();
    #endregion
		
		public Subscription()
		{
			this._ApiKeys = new EntitySet<ApiKey>(new Action<ApiKey>(this.attach_ApiKeys), new Action<ApiKey>(this.detach_ApiKeys));
			this._ApiUsageDailies = new EntitySet<ApiUsageDaily>(new Action<ApiUsageDaily>(this.attach_ApiUsageDailies), new Action<ApiUsageDaily>(this.detach_ApiUsageDailies));
			this._ApiUsageLogs = new EntitySet<ApiUsageLog>(new Action<ApiUsageLog>(this.attach_ApiUsageLogs), new Action<ApiUsageLog>(this.detach_ApiUsageLogs));
			this._Client = default(EntityRef<Client>);
			this._Plan = default(EntityRef<Plan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long SubscriptionId
		{
			get
			{
				return this._SubscriptionId;
			}
			set
			{
				if ((this._SubscriptionId != value))
				{
					this.OnSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionId = value;
					this.SendPropertyChanged("SubscriptionId");
					this.OnSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="BigInt NOT NULL")]
		public long ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					if (this._Client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientIdChanging(value);
					this.SendPropertyChanging();
					this._ClientId = value;
					this.SendPropertyChanged("ClientId");
					this.OnClientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanId", DbType="Int NOT NULL")]
		public int PlanId
		{
			get
			{
				return this._PlanId;
			}
			set
			{
				if ((this._PlanId != value))
				{
					if (this._Plan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPlanIdChanging(value);
					this.SendPropertyChanging();
					this._PlanId = value;
					this.SendPropertyChanged("PlanId");
					this.OnPlanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentPeriodStartUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime CurrentPeriodStartUtc
		{
			get
			{
				return this._CurrentPeriodStartUtc;
			}
			set
			{
				if ((this._CurrentPeriodStartUtc != value))
				{
					this.OnCurrentPeriodStartUtcChanging(value);
					this.SendPropertyChanging();
					this._CurrentPeriodStartUtc = value;
					this.SendPropertyChanged("CurrentPeriodStartUtc");
					this.OnCurrentPeriodStartUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentPeriodEndUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime CurrentPeriodEndUtc
		{
			get
			{
				return this._CurrentPeriodEndUtc;
			}
			set
			{
				if ((this._CurrentPeriodEndUtc != value))
				{
					this.OnCurrentPeriodEndUtcChanging(value);
					this.SendPropertyChanging();
					this._CurrentPeriodEndUtc = value;
					this.SendPropertyChanged("CurrentPeriodEndUtc");
					this.OnCurrentPeriodEndUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CancelAtPeriodEnd", DbType="Bit NOT NULL")]
		public bool CancelAtPeriodEnd
		{
			get
			{
				return this._CancelAtPeriodEnd;
			}
			set
			{
				if ((this._CancelAtPeriodEnd != value))
				{
					this.OnCancelAtPeriodEndChanging(value);
					this.SendPropertyChanging();
					this._CancelAtPeriodEnd = value;
					this.SendPropertyChanged("CancelAtPeriodEnd");
					this.OnCancelAtPeriodEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderSubscriptionId", DbType="NVarChar(200)")]
		public string ProviderSubscriptionId
		{
			get
			{
				return this._ProviderSubscriptionId;
			}
			set
			{
				if ((this._ProviderSubscriptionId != value))
				{
					this.OnProviderSubscriptionIdChanging(value);
					this.SendPropertyChanging();
					this._ProviderSubscriptionId = value;
					this.SendPropertyChanged("ProviderSubscriptionId");
					this.OnProviderSubscriptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime CreatedUtc
		{
			get
			{
				return this._CreatedUtc;
			}
			set
			{
				if ((this._CreatedUtc != value))
				{
					this.OnCreatedUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedUtc = value;
					this.SendPropertyChanged("CreatedUtc");
					this.OnCreatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedUtc", DbType="DateTime2(3) NOT NULL")]
		public System.DateTime UpdatedUtc
		{
			get
			{
				return this._UpdatedUtc;
			}
			set
			{
				if ((this._UpdatedUtc != value))
				{
					this.OnUpdatedUtcChanging(value);
					this.SendPropertyChanging();
					this._UpdatedUtc = value;
					this.SendPropertyChanged("UpdatedUtc");
					this.OnUpdatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiKeys_Subscription", Storage="_ApiKeys", ThisKey="SubscriptionId", OtherKey="SubscriptionId", DeleteRule="NO ACTION")]
		public EntitySet<ApiKey> ApiKeys
		{
			get
			{
				return this._ApiKeys;
			}
			set
			{
				this._ApiKeys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageDaily_Subscription", Storage="_ApiUsageDailies", ThisKey="SubscriptionId", OtherKey="SubscriptionId", DeleteRule="NO ACTION")]
		public EntitySet<ApiUsageDaily> ApiUsageDailies
		{
			get
			{
				return this._ApiUsageDailies;
			}
			set
			{
				this._ApiUsageDailies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_ApiUsageLog_Subscription", Storage="_ApiUsageLogs", ThisKey="SubscriptionId", OtherKey="SubscriptionId", DeleteRule="NO ACTION")]
		public EntitySet<ApiUsageLog> ApiUsageLogs
		{
			get
			{
				return this._ApiUsageLogs;
			}
			set
			{
				this._ApiUsageLogs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Subscriptions_Client", Storage="_Client", ThisKey="ClientId", OtherKey="ClientId", IsForeignKey=true)]
		public Client Client
		{
			get
			{
				return this._Client.Entity;
			}
			set
			{
				Client previousValue = this._Client.Entity;
				if (((previousValue != value) 
							|| (this._Client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client.Entity = null;
						previousValue.Subscriptions.Remove(this);
					}
					this._Client.Entity = value;
					if ((value != null))
					{
						value.Subscriptions.Add(this);
						this._ClientId = value.ClientId;
					}
					else
					{
						this._ClientId = default(long);
					}
					this.SendPropertyChanged("Client");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Subscriptions_Plan", Storage="_Plan", ThisKey="PlanId", OtherKey="PlanId", IsForeignKey=true)]
		public Plan Plan
		{
			get
			{
				return this._Plan.Entity;
			}
			set
			{
				Plan previousValue = this._Plan.Entity;
				if (((previousValue != value) 
							|| (this._Plan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Plan.Entity = null;
						previousValue.Subscriptions.Remove(this);
					}
					this._Plan.Entity = value;
					if ((value != null))
					{
						value.Subscriptions.Add(this);
						this._PlanId = value.PlanId;
					}
					else
					{
						this._PlanId = default(int);
					}
					this.SendPropertyChanged("Plan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ApiKeys(ApiKey entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = this;
		}
		
		private void detach_ApiKeys(ApiKey entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = null;
		}
		
		private void attach_ApiUsageDailies(ApiUsageDaily entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = this;
		}
		
		private void detach_ApiUsageDailies(ApiUsageDaily entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = null;
		}
		
		private void attach_ApiUsageLogs(ApiUsageLog entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = this;
		}
		
		private void detach_ApiUsageLogs(ApiUsageLog entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = null;
		}
	}
}
#pragma warning restore 1591
